### PR TITLE
Add support for Unix socket path

### PR DESCRIPTION
**Pull request by adellibovi**
This add dynamic support for Unix socket path, which is required by https://github.com/IBM-Swift/Kitura-net/pull/213, the idea is dynamically check if the Curl version has this feature.
Can someone point out how to proper check the availability of CURLOPT_UNIX_SOCKET_PATH?

### CODE REVIEW

**Comment by na-gupta** [comment]
I believe this should work. Could you please fix the indentation.

**Comment by adellibovi** [comment]
It looks like this doesn't work on MacOS

**Comment by na-gupta** [comment]
Is your curl version older than 7.40?

**Comment by adellibovi** [comment]
Yes

**Comment by na-gupta** [comment]
@adellibovi  I have curl version 7.54 on macOS Sierra and this builds fine for me.
I don't recall upgrading curl explicitly, but it's possible it was upgraded as part of another package.

**Comment by adellibovi** [comment]
@na-gupta it does compile, but if you try to execute it will get the wrong branch of the if.

**Comment by adellibovi** [comment]
I fixed the PR can someone review it? Maybe @rfdickerson? :)

**Comment by djones6** [comment]
@adellibovi Apologies that this stalled for so long.  I'd like to resurrect this work as part of adding Unix sockets support to Kitura.  If you are still interested in making this contribution, please could you sign the CLA?

**Comment by adellibovi** [comment]
@djones6 no prob :) the CLA should be good to go now 🥳

**Pull request merged**
